name: job-search-pipeline
channels:
  - conda-forge
dependencies:
  - python=$PYTHON_VERSION
  - pip
  - pip:
      - -e ../third_party/JobSpy
      - regex>=2024.11.6
      - pandas>=2.3.3
      - numpy>=2.4.0
      - beautifulsoup4>=4.14.3
      - pydantic>=2.12.5
      - requests>=2.32.5
      - pytest>=9.0.2
